# Generated by Django 4.2.2 on 2023-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
