# Generated by Django 4.2.2 on 2023-08-20 17:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_paid_price_alter_product_stock_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=500)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "phone_number2",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "courier",
                "ordering": ("-id",),
            },
        ),
        migrations.AlterModelOptions(
            name="consumer",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="consumerdebt",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="productconsumerprice",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_process", "in_process"),
                    ("delivering", "delivering"),
                    ("completed", "Completed"),
                ],
                default="in_process",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="consumer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shop.consumer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shop.courier",
            ),
        ),
    ]
