# Generated by Django 4.2.2 on 2023-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_courier_alter_consumer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_process", "in_process"),
                    ("delivery", "delivery"),
                    ("completed", "Completed"),
                ],
                default="in_process",
                max_length=16,
            ),
        ),
    ]
