# Generated by Django 4.2.2 on 2023-10-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_delivered_at_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumerdebt",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts",
                to="shop.consumer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_process", "Jarayonda"),
                    ("delivery", "Yetkazib berish"),
                    ("completed", "Yakunlandi"),
                    ("canceled", "Bekor qilindi"),
                ],
                default="in_process",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.order",
            ),
        ),
        migrations.AlterField(
            model_name="productconsumerprice",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.consumer"
            ),
        ),
        migrations.AlterField(
            model_name="productconsumerprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_prices",
                to="shop.product",
            ),
        ),
    ]
