# Generated by Django 4.2.2 on 2023-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_consumerdebt_consumer_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
