# Generated by Django 4.2.2 on 2023-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_order_total_price_alter_orderproduct_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="original_price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
