# Generated by Django 4.2.2 on 2023-10-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_order_original_price_orderproduct_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bulk_sell",
            field=models.BooleanField(default=False),
        ),
    ]
